spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.148.253.180:3306/yixiu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: gw_yixiu_123456
  mail:
    host: smtp.163.com
    username: 13712871903@163.com
    password: QHuQCunYFcrLUpU6
    default-encoding: UTF-8
    port: 465
    protocol: smtps
    properties:
      mail:
        stmp:
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    timeout: 3600

  data:
    redis:
      host: 8.148.253.180
      port: 6379
      password: gw_yixiu_654321
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

mybatis:
  #  mapper-locations: classpath:com/example/mapper/*.xml    #指定sql配置文件的位置
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.pojo      #指定实体类所在的包名
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    auto-mapping-behavior: full # 开启多表查询全映射
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  secret: yixiuAssistant22

# 短信服务配置
sms:
  appKey: 204946334 # 替换为你的阿里云API网关AppKey
  appSecret: viK2w1RBeUzNCxDWfBI2igLJYi7NcB4o # 替换为你的阿里云API网关AppSecret
  templateId: TPL_0001 # 短信模板ID，调试模板
  appcode: 0f84c9de1f75436f9a32c15addb182ff #appcode
  host: https://smsv2.market.alicloudapi.com #这个是简单认证请求地址，示例中为调试地址
  path: /sms/sendv2

resources-path:
  avatar: D:/ideaProject/yixiuAssist/image/avatar/
  request: D:/ideaProject/yixiuAssist/image/request/
  linux_avatar: /usr/yixiuAssist/image/avatar/
  linux_request: /usr/yixiuAssist/image/request/

