server {
    listen 443 ssl;
    server_name _;

    client_max_body_size 5m;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # 访问 /yixiu-site 自动补 /
    location = /yixiu-site {
        return 301 /yixiu-site/;
    }

    # Vue3 前端（base = /yixiu-site/）
    location ^~ /yixiu-site/ {
            alias /usr/share/nginx/html/;
            index index.html;
            try_files $uri $uri/ /yixiu-site/index.html;
        }

    # 静态资源代理（图片）- 新增
         location /img/ {
             proxy_pass http://yixiu-server:8080/img/;
             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         }

    # 后端接口
    location /api/ {
            proxy_pass http://yixiu-server:8080/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_set_header X-Forwarded-Proto $scheme;
        }
}

# 可选：HTTP 自动跳转 HTTPS
server {
    listen 80;
    server_name _;
    return 301 https://8.148.253.180:8443$request_uri;
}